### ISSUE TITLE
Programma rimane su caricamento dell'interfaccia in corso

### ISSUE THREAD

**Issue by mr-brune** [RedSquirrel87/manga-downloader#800]
Succede solo se si avvia il programma in modo pulito scaricando lo zip

allego errore succede sia su debian 12 che windows 11

`Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/apache/commons/collections/list/TreeList
        at mainpackage.ChaptersTabelModel.<init>(ChaptersTabelModel.java:37)
        at mainpackage.NewJFrame.initComponents(NewJFrame.java:5221)
        at mainpackage.NewJFrame.<init>(NewJFrame.java:219)
        at mainpackage.NewJFrame$229$1.run(NewJFrame.java:13615)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections.list.TreeList
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more
`

**Comment by RedSquirrel87** [comment]
Che versione di Java hai installato? Strano che non ci siano le classi per la TreeList, non pensavo fossero così recenti.
Risolvi comunque installando l'ultima versione del JDK (dovrebbe essere la 20): https://www.oracle.com/it/java/technologies/downloads/
Ora comunque cerco da che versione è stata introdotta questa classe che se non è nella JRE base vedo di tornare all'arraylist classico

**Comment by RedSquirrel87** [comment]
Ah no, ho detto una cavolata scusa, visto solo ora che è una libreria esterna di apache, ecco perché non la trova. Vedo di fixare appena possibile

**Comment by RedSquirrel87** [comment]
Ho appena rilasciato un nuovo update che implementa la libreria mancante, fammi sapere se adesso ti funziona per favore 👍
