### ISSUE TITLE
Shueisha no longer working?

### ISSUE THREAD

**Issue by pjft** [RedSquirrel87/manga-downloader#831]
Hi.

Apologies, unsure what's happening as this has worked all the time until now. Shueisha now seems to no longer work, and I'm not sure why. It works well on the web, but it seems that it's returning a 404 on the logs after a redirect of sorts.

Hope this helps, but happy to share more details.

URL: 
https://mangaplus.shueisha.co.jp/titles/100127

Log:

```
[Mon May 27 09:46:24 WEST 2024] Program started.
[Mon May 27 09:46:24 WEST 2024] MangaDownloader v63.1
[Mon May 27 09:46:24 WEST 2024] OS: Mac OS X (x86_64) | JVM: 1.8.0_341
[Mon May 27 09:46:25 WEST 2024] Patreon status: no linked Patreon account.
[Mon May 27 09:46:27 WEST 2024] [DB] Database current version: 5
[Mon May 27 09:46:35 WEST 2024] Loading manga from https://mangaplus.shueisha.co.jp/titles/100127
[Mon May 27 09:47:34 WEST 2024] HTTP response code: 200
[Mon May 27 09:47:34 WEST 2024] Framework: MANGAPLUS
[Mon May 27 09:47:35 WEST 2024] HTTP response code: 404
[Mon May 27 09:47:35 WEST 2024] Error while getting chapters list:
java.lang.NullPointerException
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at mainpackage.MangaPlusSerializer$Response.parseFrom(MangaPlusSerializer.java:45103)
	at mainpackage.MangaPlus.GetChapters(MangaPlus.java:250)
	at mainpackage.NewJFrame.GetChaptersList(NewJFrame.java:9602)
	at mainpackage.NewJFrame.GetChaptersList(NewJFrame.java:9248)
	at mainpackage.NewJFrame.access$23300(NewJFrame.java:165)
	at mainpackage.NewJFrame$212.run(NewJFrame.java:10017)
	at java.lang.Thread.run(Thread.java:750)
[Mon May 27 09:47:35 WEST 2024] Error: NULL chapters list.
[Mon May 27 09:47:44 WEST 2024] Loading manga from https://mangaplus.shueisha.co.jp/titles/100127
[Mon May 27 09:48:01 WEST 2024] HTTP response code: 200
[Mon May 27 09:48:01 WEST 2024] Framework: MANGAPLUS
[Mon May 27 09:48:02 WEST 2024] HTTP response code: 404
[Mon May 27 09:48:02 WEST 2024] Error while getting chapters list:
java.lang.NullPointerException
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at mainpackage.MangaPlusSerializer$Response.parseFrom(MangaPlusSerializer.java:45103)
	at mainpackage.MangaPlus.GetChapters(MangaPlus.java:250)
	at mainpackage.NewJFrame.GetChaptersList(NewJFrame.java:9602)
	at mainpackage.NewJFrame.GetChaptersList(NewJFrame.java:9248)
	at mainpackage.NewJFrame.access$23300(NewJFrame.java:165)
	at mainpackage.NewJFrame$212.run(NewJFrame.java:10017)
	at java.lang.Thread.run(Thread.java:750)
[Mon May 27 09:48:02 WEST 2024] Error: NULL chapters list.
```

**Comment by pjft** [comment]
From what I understand, the old API link doesn't work anymore. If I find out more I'll report:

https://jumpg-webapi.tokyo-cdn.com/api returns 404

**Comment by RedSquirrel87** [comment]
Thank you for reporting the issue, hoping they haven't changed too many things in their API system because last time it took me almost six months to get it working 😅

**Comment by pjft** [comment]
Oh no, I'm so sorry to hear that 😅 

From what I understand, 

for Manga

https://mangaplus.shueisha.co.jp/titles/100003

you can use the ID and the following API call lists the results:

https://jumpg-webapi.tokyo-cdn.com/api/title_detailV3?title_id=100003

and then, for a given chapter returned by the API, say:

https://mangaplus.shueisha.co.jp/drm/title/100003/chapter/1021118/chapter_thumbnail/348100.jpg?key=ec8650d62dbec0ad32da527ea5d9dcfa&duration=864000

you use this with the chapter ID to list the pages:

https://jumpg-webapi.tokyo-cdn.com/api/manga_viewer?chapter_id=1021118&split=yes&img_quality=super_high

so I *hope* that things haven't changed significantly, other than potentially the API URL. But maybe these links can help?

I get a 401 on the web calling these, but I suppose that's to be expected as I'm not storing any context on my end.

Let me know if this helps or what else I can do to test!

Thanks :)

**Comment by RedSquirrel87** [comment]
Yeah from what I've seen at a first glance it looks like they simply changed the API URL by adding a 'V3' at the end. As soon as I'm at the PC I'll try to modify it and see if everything works. If that's the only issue, it will be fixed in tonight's nightly build 👍

**Comment by pjft** [comment]
Thank you! Looking forward to hearing from you, and thanks for keeping me posted. :)

**Comment by RedSquirrel87** [comment]
I can confirm that this issue has now been resolved in the nightly builds and will therefore be fixed also in the next public release 👍

**Comment by pjft** [comment]
Thank you for the prompt acknowledgement and workaround! I look forward to the release. :)
