### ISSUE TITLE
Il programma rimane su "caricamento dell'interfaccia in corso"

### ISSUE THREAD

**Issue by Nuriell** [RedSquirrel87/manga-downloader#859]
Ho recentemente reinstallato il PC con Windows 11 e ora ogni volta che avvio il programma rimane sul caricamento dell'interfaccia.

Ho installato sia JRE 8u421 che SDK 23, sia singolarmente che assieme, nulla da fare.

Questo accade sia con la vecchia cartella che il programma "pulito" scaricato da web.

Ho provato a cercare un log ma non ho trovato nulla nella cartella e non so dove trovarlo in java, in caso aspetste dove trovarlo per favore ditemelo che così lo posto.

Ho provato a lasciarlo macinare un po' di minuti intanto che scrivevo questo post ma nulla, quando l'ho chiuso forzatamente è crashato explorer.

**Comment by RedSquirrel87** [comment]
Puoi farmi uno screenshot della cartella in cui hai il programma? Non vorrei mancasse qualche libreria (è l'unica cosa che mi viene in mente leggendo la tua descrizione del problema e non avendo un log da analizzare)

**Comment by Nuriell** [comment]
Certo, ecco sia la cartella principale che le librerie:

![Manga Downloader Lib Folder](https://github.com/user-attachments/assets/c66b1372-08c5-4baf-927a-e2235f99d46f)
![Manga Downloader Main Folder](https://github.com/user-attachments/assets/dbf97e83-c54f-44d1-bcb2-00d501b8cb74)

Ah, se faccio partire il programma scaricato da web per il primo avvio non scarica altro oltre questo: 

![Manga Downloader Clean Install Lib](https://github.com/user-attachments/assets/3a3dc44e-e093-47f9-b11b-8a61196bcd7c)

**Comment by RedSquirrel87** [comment]
Ok le librerie sono apposto, il fatto che ti abbia scaricato anche le altre significa che ha superato il primo avvio. A questo punto però ammetto che non ho la minima idea di cosa possa causarlo allora. Bisogna analizzare a livello di terminale se hai voglia (è un procedimento un po' articolato), dovresti aprire il prompt dei comandi di Windows (digitando cmd nel menù di Windows), poi cambiare posizione per andare nella cartella dove hai i file del programma usando il comando:
`cd C:\percorso\dove\hai\i\file\del\programma`
e a quel punto (dopo che dal prompt sei entrato nella cartella) lanciare il programma dal prompt digitando:
`java -jar main.jar`
così facendo qualsiasi errore che blocchi l'avvio del programma verrà stampato all'interno del prompt dei comandi e possiamo capire dov'è l'intoppo

**Comment by Nuriell** [comment]
Here we go,  think the problem is what i bolded but i already gave access at the windows firewall to the program:

D:\Programs\Manga Downloader>java -jar main.jar
ott 15, 2024 3:39:06 PM sun.awt.shell.Win32ShellFolderManager2 getNetwork
**WARNING: Cannot access 'Network'**
java.io.IOException: Could not get shell folder ID list
        at java.desktop/sun.awt.shell.Win32ShellFolder2.getFileSystemPath0(Native Method)
        at java.desktop/sun.awt.shell.Win32ShellFolder2$7.call(Win32ShellFolder2.java:666)
        at java.desktop/sun.awt.shell.Win32ShellFolder2$7.call(Win32ShellFolder2.java:664)
        at java.desktop/sun.awt.shell.Win32ShellFolderManager2$ComInvoker.invoke(Win32ShellFolderManager2.java:630)
        at java.desktop/sun.awt.shell.ShellFolder.invoke(ShellFolder.java:532)
        at java.desktop/sun.awt.shell.Win32ShellFolder2.getFileSystemPath(Win32ShellFolder2.java:664)
        at java.desktop/sun.awt.shell.Win32ShellFolder2.composePathForCsidl(Win32ShellFolder2.java:276)
        at java.desktop/sun.awt.shell.Win32ShellFolder2.<init>(Win32ShellFolder2.java:289)
        at java.desktop/sun.awt.shell.Win32ShellFolderManager2.getNetwork(Win32ShellFolderManager2.java:222)
        at java.desktop/sun.awt.shell.Win32ShellFolder2.getFileSystemPath(Win32ShellFolder2.java:630)
        at java.desktop/sun.awt.shell.Win32ShellFolder2$2.call(Win32ShellFolder2.java:354)
        at java.desktop/sun.awt.shell.Win32ShellFolder2$2.call(Win32ShellFolder2.java:352)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.desktop/sun.awt.shell.Win32ShellFolderManager2$ComInvoker$1.run(Win32ShellFolderManager2.java:599)
        at java.base/java.lang.Thread.run(Thread.java:1575)

Exception in thread "Thread-0" java.lang.NullPointerException: Cannot invoke "sun.awt.shell.Win32ShellFolder2.getIShellFolder()" because the return value of "sun.awt.shell.Win32ShellFolderManager2.getNetwork()" is null
        at java.desktop/sun.awt.shell.Win32ShellFolder2.getFileSystemPath(Win32ShellFolder2.java:630)
        at java.desktop/sun.awt.shell.Win32ShellFolder2$2.call(Win32ShellFolder2.java:354)
        at java.desktop/sun.awt.shell.Win32ShellFolder2$2.call(Win32ShellFolder2.java:352)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.desktop/sun.awt.shell.Win32ShellFolderManager2$ComInvoker$1.run(Win32ShellFolderManager2.java:599)
        at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by Nuriell** [comment]
Questo invece è il log del programma da installazione free che non scarica le librerie:

D:\Programs>cd mangadownloader

D:\Programs\MangaDownloader>java -jar main.jar
java.io.FileNotFoundException: settings.dat (Impossibile trovare il file specificato)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at mainpackage.MyProperties.<init>(MyProperties.java:20)
        at mainpackage.NewJFrame.<clinit>(NewJFrame.java:165)
ott 15, 2024 3:42:27 PM sun.awt.shell.Win32ShellFolderManager2 getNetwork
WARNING: Cannot access 'Network'
java.io.IOException: Could not get shell folder ID list
        at java.desktop/sun.awt.shell.Win32ShellFolder2.getFileSystemPath0(Native Method)
        at java.desktop/sun.awt.shell.Win32ShellFolder2$7.call(Win32ShellFolder2.java:666)
        at java.desktop/sun.awt.shell.Win32ShellFolder2$7.call(Win32ShellFolder2.java:664)
        at java.desktop/sun.awt.shell.Win32ShellFolderManager2$ComInvoker.invoke(Win32ShellFolderManager2.java:630)
        at java.desktop/sun.awt.shell.ShellFolder.invoke(ShellFolder.java:532)
        at java.desktop/sun.awt.shell.Win32ShellFolder2.getFileSystemPath(Win32ShellFolder2.java:664)
        at java.desktop/sun.awt.shell.Win32ShellFolder2.composePathForCsidl(Win32ShellFolder2.java:276)
        at java.desktop/sun.awt.shell.Win32ShellFolder2.<init>(Win32ShellFolder2.java:289)
        at java.desktop/sun.awt.shell.Win32ShellFolderManager2.getNetwork(Win32ShellFolderManager2.java:222)
        at java.desktop/sun.awt.shell.Win32ShellFolder2.getFileSystemPath(Win32ShellFolder2.java:630)
        at java.desktop/sun.awt.shell.Win32ShellFolder2$2.call(Win32ShellFolder2.java:354)
        at java.desktop/sun.awt.shell.Win32ShellFolder2$2.call(Win32ShellFolder2.java:352)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.desktop/sun.awt.shell.Win32ShellFolderManager2$ComInvoker$1.run(Win32ShellFolderManager2.java:599)
        at java.base/java.lang.Thread.run(Thread.java:1575)

Exception in thread "Thread-0" java.lang.NullPointerException: Cannot invoke "sun.awt.shell.Win32ShellFolder2.getIShellFolder()" because the return value of "sun.awt.shell.Win32ShellFolderManager2.getNetwork()" is null
        at java.desktop/sun.awt.shell.Win32ShellFolder2.getFileSystemPath(Win32ShellFolder2.java:630)
        at java.desktop/sun.awt.shell.Win32ShellFolder2$2.call(Win32ShellFolder2.java:354)
        at java.desktop/sun.awt.shell.Win32ShellFolder2$2.call(Win32ShellFolder2.java:352)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.desktop/sun.awt.shell.Win32ShellFolderManager2$ComInvoker$1.run(Win32ShellFolderManager2.java:599)
        at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by RedSquirrel87** [comment]
Ammetto che è la prima volta in vita mia che leggo di un errore simile, a cercare sul web ho trovato questa spiegazione:

> If you're getting this message, you probably have recently replaced a hard drive or removed a flash drive that you had previously configured for some personal settings or any number of other things than can confuse Windows and/or the Java VM that ECMLink works under.

Mi confermi che hai cambiato Hard Disk (o SSD) ultimamente?

**Comment by RedSquirrel87** [comment]
Ho cercato un po' sul web e come soluzione al problema consigliano questo: avvia l'editor del registro di sistema digitando regedit nel menù di Windows (come prima hai fatto con cmd per intenderci).
A quel punto nell'editor vai sulla casella in alto:
![image](https://github.com/user-attachments/assets/0a72998e-13fd-451a-bc58-09da02159784)
e incollaci questa stringa:
`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders`
dai INVIO e ora nella colonna di destra dovrebbe apparirti una lista di "scorciatoie" di sistema come queste:

![image](https://github.com/user-attachments/assets/328dfdb2-0555-4f3d-86be-facedba276bb)

All'interno di questa lista devi cancellare (tasto destro sul nome e fai **Elimina**) tutte quelle stringhe che fanno riferimento a vecchi HDD/SDD o comunque a lettere che ora non esistono più nel tuo PC dopo la reinstallazione, così da ripulire tutti i collegamenti "rotti" diciamo. Una volta fatto chiudi l'editor per salvare i cambiamenti e riavvia il PC, così dovrebbe risolversi quell'errore

**Comment by Nuriell** [comment]
Non ho cambiato Hard Disk e tutte le cartelle sono standard: 
![User Shell Folders](https://github.com/user-attachments/assets/622ea61a-ef8c-4f9c-9b38-6c47866631b2)

Perà ho reinstallato Windows e ho un nuovo profilo, forse è quello visto che prima avevo variabili d'ambiente non standard, provo a settare quelle e vedo che succede.

**Comment by RedSquirrel87** [comment]
ma anche dopo la formattazione ti da sempre lo stesso errore nel prompt (ossia java.io.IOException: Could not get shell folder ID list)?
A vedere la tua lista di variabili d'ambiente lì penso che il problema potrebbe essere quel %USERPROFILE%, magari Java non lo interpreta per bene (sto ipotizzando anche io, onestamente mai avuto a che fare con un simile errore).
Nel prompt dei comandi prova a digitare:
`echo %USERPROFILE%`
e vedi se ti dice a cosa corrisponde quella variabile, in caso potresti provare a sostituirla in quella lista (nel senso che ad esempio a me corrisponde a C:\Users\redsq quindi andrei a sostituire a _%USERPROFILE%\Downloads_ il valore _C:\Users\redsq\Downloads_ e via dicendo). Purtroppo non trovo altre possibili soluzioni su internet ad un simile problema, quindi sto andando a tentativi

**Comment by RedSquirrel87** [comment]
Aspetta mi è venuta un'idea forse, a leggere meglio il tuo log il problema sembra specifico alla variabile Network che in effetti non compare nella tua lista di variabili (mi riferisco quando dice `WARNING: Cannot access 'Network'` e successivamente `Exception in thread "Thread-0" java.lang.NullPointerException: Cannot invoke "sun.awt.shell.Win32ShellFolder2.getIShellFolder()" because the return value of "sun.awt.shell.Win32ShellFolderManager2.getNetwork()" is null`) quindi prova a fare questo: sempre nella lista delle variabili lì nell'editor di sistema aggiungi una nuova voce (tasto destro -> Nuovo -> Valore stringa espandibile), come nome dagli **Network** e come valore uno qualsiasi (ad esempio **%USERPROFILE%\Downloads**). Dopodiché salva e riavvia e prova a vedere se funziona e in caso non funzioni se l'errore rimane lo stesso (soprattutto se dice ancora che non può accedere a Network)

**Comment by Nuriell** [comment]
Alura, l'errore è lo stesso, non è cambiato nulla.

Ho midificato le variabili d0ambiente come hai suggerito, nulla nemmeno in questo caso.

Provato a mettere la voce Network, nulla, e stesso errore, non so dove sbattere la testa.

**Comment by RedSquirrel87** [comment]
Purtroppo anche online si trova pochissima documentazione riguardo questo errore, Google stesso cercando l'errore su sun.awt.shell.Win32ShellFolderManager2.getNetwork() = null ritorna pochissimi risultati, qui pure dicono che sembra essere un raro bug di Java con alcune versioni di Windows: https://github.com/skylot/jadx/issues/1709
Leggendo invece da qui https://bugs.openjdk.org/browse/JDK-8179014 dicono sia un problema solo con il tema Windows di default, quindi possiamo provare un ultimissimo tentativo: apri il file settings.dat con notepad e modifica il valore 
`s|theme=com.sun.java.swing.plaf.windows.WindowsLookAndFeel`
in:
`s|theme=com.formdev.flatlaf.FlatLightLaf`
salva i cambiamenti e prova a riavviare il programma

**Comment by Nuriell** [comment]
Ok, questo è interessante, io non ho quella voce nel file di configurazione, ho provato a inserirle immediatamente sotto la data ma nulla.

Ecco tutto quello che c'è dentro al file di base

#--- PLEASE DO NOT EDIT THIS FILE MANUALLY! ---
#Sat Sep 07 12:50:40 CEST 2024
**(Ho inserito le voci qui, questa riga non esiste nel file di configurazione)**
b|page_usechapcustomname=false
i|CLVL=9
b|guess=false
s|patreon_page_pattern=|\#|
i|page_maxchars=50
b|FIRST=false
b|patreon_conc=false
b|page_include_uploader=false
s|general_emptyrep=X
b|patreon_page_usecustomrules=false
i|pause_start=5
i|startup=0
b|page_include_manga=false
b|chap_include_uploader=false
b|page_generatefromfields=false
l|autobackuplast=1725659039809
i|ROWH=20
b|chap_include_date=false
b|chap_usemangacustomname=false
i|READTO=15
b|chap_createfolder=true
i|THREADS=2
s|VER=64.7
s|page_pattern=|\#|
i|DIVIDER=527
i|HISTSIZE=5
b|manga_createfolder=true
b|onlyfolders=false
b|page_include_group=false
b|chap_include_lang=false
b|ex_suffix=true
i|cdelay=0
i|general_replacer=0
b|chap_usecustomrules=false
s|conc_pattern=|M| - |C| (|L|)
i|schedule_radio=0
s|last103=D\:\\IMPORT\\AAA Images\\AAA Images
i|chap_rules=0
b|page_include_chapter=false
i|framew=0
s|last101=https\://likemanga.io/no-game-no-life-21401/|\:|https\://likemanga.io/accel-world-17147/|\:|https\://www.mangaworld.ac/manga/3142/white-dragon|\:|https\://www.mangaworld.ac/manga/1738/solo-leveling|\:|https\://www.mangaworld.ac/manga/1389/busou-renkin
i|general_separator=3
b|show_confirm=false
i|FONTSIZE=11
b|ask=false
i|frameh=0
b|manga_usemangacustomname=false
i|IMGQ=95
i|RETRIES=3
b|conc_usemangacustomname=false
b|page_include_lang=false
b|chap_generatefromfields=true
b|migration=true
b|page_generatefrompattern=true
b|ex_skip=false
b|manga_usecustomrules=false
s|PATH=D\:\\IMPORT\\AAA Images\\AAA Images
b|chap_keeponlynumbers=false
b|conc=false
b|page_usemangacustomname=false
i|PAUSE=1
b|pause_random=false
b|patreon_page_generatefrompattern=true
b|ZIP=false
i|chap_maxchars=100
i|page_numberposition=0
i|conc_maxchars=100
i|pause_end=30
i|manga_maxchars=50
b|chap_setdigitspadding=false
b|conc_sameofchapter=true
i|OUT=1
b|general_empty=false
b|chap_include_manga=false
i|manga_rules=0
b|renaming_warn=false
b|blackfix=true
i|page_rules=0
b|patreon_page_generatefromfields=false
b|show_completedwitherrors=true
b|chap_generatefrompattern=false
s|chap_pattern=|M| - |C| (|L|)
b|conc_usechapcustomname=false
b|ex_replace=false
b|page_usecustomrules=false
b|chap_include_group=false
s|lang=Qualsiasi
b|chap_removemanganame=false
i|CONNTO=15

**Comment by RedSquirrel87** [comment]
Ma quando avvii il programma la splash screen di caricamento dell'interfaccia è cambiata di tema? Se è cambiata significa che te lo ha preso correttamente il nuovo tema ma comunque non fixa il problema allora 😔

**Comment by Nuriell** [comment]
Queste sono le due schermateche vedo quando si apre il programma:
![Manga Downloader Splash](https://github.com/user-attachments/assets/22b72d93-724d-4312-85e3-88cb88d2a20f)
e poi
![Manga Downloader Splash](https://github.com/user-attachments/assets/f41ea221-1719-45e6-8623-c6124d30725f)

**Comment by RedSquirrel87** [comment]
Ok forse c'è ancora speranza allora, dallo screenshot non mi sembra che ti abbia preso il tema diverso, quindi possiamo provare un'altra cosa. Scarica questo mio settings, estrailo (ho dovuto zipparlo perché Github non accetta il formato .dat) e sostituiscilo al file settings.dat che dovrebbe essere già presente all'interno della cartella del programma: 
[settings.zip](https://github.com/user-attachments/files/17390718/settings.zip)
Poi avvia il programma e la splash screen da standard così:
![FsrGVH3TYL](https://github.com/user-attachments/assets/d1d58f17-9a0a-4f0d-a263-6f5c2ae2e700)
dovrebbe apparirti scura invece (se ha preso il tema giusto), così:
![EDNXmag9o1](https://github.com/user-attachments/assets/a83f55bb-08ca-4b35-99de-6b8e9652eda9)
Così proviamo a vedere se cambiando il tema di default funziona 👍

**Comment by Nuriell** [comment]
Se uso la versione base pulita fa qualcosa, scarica le prime librerie, cambia colore la schermata di caricamento interfaccia diventando nera... e bon, si ferma lì, non riesco a fare altro.

La cosa bella èp che la nuova installazione di Windows 11 che ho fatto è MENO modificata delal precedente perché non ho installato un sacco di cose che non mi servono spesso e in caso le installerà al momento del bisogno. (così ho anche un punto di salvataggio per fareun repulisti totale una volta all'anno).

Se tiviene in mente altro per provar a risolvere fammelo sapere, per ora io tengo tutto lì e spero che in futuro si sblocchi la situazione, capita spesso che qualcosa in Windows si rompa e torni utilizzabile in futuro (come i video di Steam che mi funzionavano prima ma con questa nuova installazione non c'era verso, poi son partiti senza una plausibile spiegazione).

Grazie per il tuo tempo.

**Comment by Nuriell** [comment]
Ottimo a spaersi, quando farai i cambiamenti scrivi qualcosa qui, io tengo salvato il thread e ogni tanto lo guardi, così posso fare i test del caso.

Grazie mille ancora per la tua disponibilità.

**Comment by Nuriell** [comment]
PS: Visto che ti stai facendo il mazzo e mi sembra giusto mi sono appena iscritto al tier Manga Downloader Premium su Patreon, almeno ti viene qualcosa in tasca dall'aiutarmi.

Potrò tenerlo solo uno o due mesi ma fin che posso, ed è anche un buon modo di provare patreon visto che è la prima volta che m'iscrivo e sto pensando di provare altri altri creator in futuro (QDSS).

**Comment by RedSquirrel87** [comment]
Ma no figurati, tento di risolvere il problema perché ovviamente mi piacerebbe che il programma possa essere utilizzato, altrimenti ha poco senso che esista 😄
Ti ringrazio davvero per il supporto, purtroppo si, l'ultima nightly è praticamente identica alla versione pubblica perché nell'ultimo mese a causa di problematiche varie che ho spiegato su Patreon proprio non sono riuscito a lavorare quasi per nulla al programma, ma ho ripreso da qualche giorno e attualmente è in sviluppo una nuova versione "major" che introdurrà diverse migliorie richieste ormai da tanti anni, quindi le nuove nightly non tarderanno ad arrivare nelle prossime settimane (il tempo di rendere di nuovo almeno avviabile il programma, visto che dai cambiamenti che sto facendo in questi giorni la versione in sviluppo è praticamente rotta in gran parte della funzione di download che poi è la funzione principale del programma xD). E non devi scusarti se toglierai l'abbonamento, ci mancherebbe pure, so bene che una spesa mensile al giorno d'oggi si somma a mille mila più importanti, piuttosto grazie davvero per aver deciso di supportare il progetto, lo apprezzo davvero 🙏

**Comment by RedSquirrel87** [comment]
Ho appena rilasciato la nuova nightly build su Patreon, ho spostato l'inizializzazione del programma come dicevo l'altra volta, quando hai tempo controlla se ti funziona o, in caso ti desse errore, se è sempre lo stesso identico

**Comment by Nuriell** [comment]
Funziona tutto perfettamente!!!

Grazie, sei un mito.

Come dicevi l'unica cosa che non posso fare è cambiare la cartella di download dal programma ma mi è bastato editare il file d'impostaizone manualmente e d è andato come un fulmine.

Ora aspetto la stabile e siamo a cammello.

**Comment by RedSquirrel87** [comment]
v70 just released
