### ISSUE TITLE
Unable to load list of chapters

### ISSUE THREAD

**Issue by joanyp** [RedSquirrel87/manga-downloader#876]
I'm unable to load the chapters from MangaDex and it is not specific to just one manga, Basically all the mangas. I can access MangaDex on my chrome; Hence, I'm not sure what is the issue.

Log as below:
[Tue Dec 31 00:06:45 GMT+08:00 2024] Loading manga from https://mangadex.org/title/b0b721ff-c388-4486-aa0f-c2b0bb321512/sousou-no-frieren
Dec 31, 2024 12:06:45 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://mangadex.org:443: Connection reset
Dec 31, 2024 12:06:45 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://mangadex.org:443
Dec 31, 2024 12:06:45 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://mangadex.org:443: Connection reset
Dec 31, 2024 12:06:45 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://mangadex.org:443
[Tue Dec 31 00:06:45 GMT+08:00 2024] Error while performing HTTP HEAD request:
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:462)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1422)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:313)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at mainpackage.Manga.GetResponseCode(Manga.java:542)
	at mainpackage.NewJFrame$224.run(NewJFrame.java:10115)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[Tue Dec 31 00:06:45 GMT+08:00 2024] HTTP response code: -1
[Tue Dec 31 00:06:45 GMT+08:00 2024] Framework: MANGADEX
Dec 31, 2024 12:06:45 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://api.mangadex.org:443: Connection reset
Dec 31, 2024 12:06:45 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://api.mangadex.org:443
Dec 31, 2024 12:06:45 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://api.mangadex.org:443: Connection reset
Dec 31, 2024 12:06:45 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://api.mangadex.org:443
Dec 31, 2024 12:06:45 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://api.mangadex.org:443: Connection reset
Dec 31, 2024 12:06:45 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://api.mangadex.org:443
[Tue Dec 31 00:06:45 GMT+08:00 2024] Error while performing HTTP GET request:
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:462)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1422)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:313)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at mainpackage.Manga.GetHTML(Manga.java:615)
	at mainpackage.Manga.GetHTMLFromHost(Manga.java:452)
	at mainpackage.MangaDex.GetChapters(MangaDex.java:70)
	at mainpackage.MangaDex.GetChapters(MangaDex.java:50)
	at mainpackage.NewJFrame.GetChaptersList(NewJFrame.java:9828)
	at mainpackage.NewJFrame.GetChaptersList(NewJFrame.java:9811)
	at mainpackage.NewJFrame.access$24400(NewJFrame.java:160)
	at mainpackage.NewJFrame$224.run(NewJFrame.java:10281)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[Tue Dec 31 00:06:45 GMT+08:00 2024] Error: NULL HTML code (1).
[Tue Dec 31 00:06:45 GMT+08:00 2024] Error: NULL chapters list.

**Comment by RedSquirrel87** [comment]
Hello, from what I can see in the log, it’s an error due to SSL certificates, which you probably don’t have in your JAVA installation. This is usually because you’re using JRE instead of JDK. Unfortunately, I can’t tell you for sure since the log where it says so is truncated at the beginning, so I don’t know which version you’re using. However, give a look at the first lines of the log, if your JVM version is 1.8 or similar, then you’re using JRE. In that case, install JDK instead (which is now at version 23), and you should solve the issues with SSL certificates. You can download JDK for free from Oracle's website here: [](https://www.oracle.com/java/technologies/downloads/#jdk23-windows)

**Comment by joanyp** [comment]
Hi thanks for the troubleshoot! I managed to load the chapters but now having trouble downloading them. It goes to error immediately when I click on download. Here is the log:

[Tue Dec 31 07:44:08 GMT+08:00 2024] Program started.
[Tue Dec 31 07:44:08 GMT+08:00 2024] MangaDownloader v70.1
[Tue Dec 31 07:44:08 GMT+08:00 2024] OS: Windows 10 (amd64) | JVM: 23.0.1
[Tue Dec 31 07:44:08 GMT+08:00 2024] Patreon status: no linked Patreon account.
[Tue Dec 31 07:44:09 GMT+08:00 2024] Patreon status: no linked Patreon account.
[Tue Dec 31 07:44:09 GMT+08:00 2024] [DB] Database current version: 5
[Tue Dec 31 07:44:25 GMT+08:00 2024] Loading manga from https://mangadex.org/title/7f30dfc3-0b80-4dcc-a3b9-0cd746fac005/detective-conan
[Tue Dec 31 07:44:25 GMT+08:00 2024] HTTP response code: -405
[Tue Dec 31 07:44:25 GMT+08:00 2024] Framework: MANGADEX
[Tue Dec 31 07:44:29 GMT+08:00 2024] 5525 chapters found.
[Tue Dec 31 07:47:14 GMT+08:00 2024] Download started for chapter Vol. 104 Ch. 1112: The Spilt Truth
[Tue Dec 31 07:47:14 GMT+08:00 2024] Download started for chapter Vol. 104 Ch. 1111: The Flowerbed's Mystery
[Tue Dec 31 07:47:14 GMT+08:00 2024] Error while performing HTTP GET request:
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:462)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1422)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:313)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at mainpackage.Manga.GetHTML(Manga.java:615)
	at mainpackage.Manga.GetHTMLFromHost(Manga.java:452)
	at mainpackage.MangaDex.GetPages(MangaDex.java:254)
	at mainpackage.Job.run(Job.java:473)
	at mainpackage.ThreadManager.lambda$checkAndRunNextJob$0(ThreadManager.java:114)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[Tue Dec 31 07:47:14 GMT+08:00 2024] Error: NULL HTML code (3).

**Comment by RedSquirrel87** [comment]
From the log the error seems to be the same:

> Unsupported or unrecognized SSL message

Are you using any proxy, VPN or similar for your connection?

**Comment by joanyp** [comment]
No... I've disabled all proxy and I'm not using any VPN. I cant load the chapters again T_T

Latest log:
[Tue Dec 31 10:18:43 GMT+08:00 2024] Program started.
[Tue Dec 31 10:18:43 GMT+08:00 2024] MangaDownloader v70.1
[Tue Dec 31 10:18:43 GMT+08:00 2024] OS: Windows 10 (amd64) | JVM: 23.0.1
[Tue Dec 31 10:18:44 GMT+08:00 2024] Patreon status: no linked Patreon account.
[Tue Dec 31 10:18:44 GMT+08:00 2024] Patreon status: no linked Patreon account.
[Tue Dec 31 10:18:44 GMT+08:00 2024] [DB] Database current version: 5
[Tue Dec 31 10:18:53 GMT+08:00 2024] Loading manga from https://mangadex.org/title/6e96f17a-0aa1-411a-82bd-1171c0ee95f3/37-year-old-kindaichi-case-files
[Tue Dec 31 10:18:54 GMT+08:00 2024] Error while performing HTTP HEAD request:
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:462)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1422)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:313)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at mainpackage.Manga.GetResponseCode(Manga.java:542)
	at mainpackage.NewJFrame$224.run(NewJFrame.java:10115)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[Tue Dec 31 10:18:54 GMT+08:00 2024] HTTP response code: -1
[Tue Dec 31 10:18:54 GMT+08:00 2024] Framework: MANGADEX
Dec 31, 2024 10:18:54 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://api.mangadex.org:443: Connection reset
Dec 31, 2024 10:18:54 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://api.mangadex.org:443
[Tue Dec 31 10:18:54 GMT+08:00 2024] Error while performing HTTP GET request:
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:462)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1422)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:313)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at mainpackage.Manga.GetHTML(Manga.java:615)
	at mainpackage.Manga.GetHTMLFromHost(Manga.java:452)
	at mainpackage.MangaDex.GetChapters(MangaDex.java:70)
	at mainpackage.MangaDex.GetChapters(MangaDex.java:50)
	at mainpackage.NewJFrame.GetChaptersList(NewJFrame.java:9828)
	at mainpackage.NewJFrame.GetChaptersList(NewJFrame.java:9811)
	at mainpackage.NewJFrame.access$24400(NewJFrame.java:160)
	at mainpackage.NewJFrame$224.run(NewJFrame.java:10281)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[Tue Dec 31 10:18:54 GMT+08:00 2024] Error: NULL HTML code (1).
[Tue Dec 31 10:18:54 GMT+08:00 2024] Error: NULL chapters list.

**Comment by joanyp** [comment]
I manage to bypass the issue using VPN... I think it has probably got to do with my country's network settings?

**Comment by RedSquirrel87** [comment]
Yes, Mangadex has been blocked in several countries (for example, it is also blocked via DNS here in Italy, in fact I need to use Google DNS to access it), so that might indeed be the cause. Out of curiosity, which country are you from? This way, if another user will have the same issue in the future, I can inform them. 
P.s.: have you tried using the option to "bypass DNS protection" you can find in the Extra -> Mangadex menu? It usually doesn't cause an SSL error, but it's worth a try, it might work even with this type of error (though I doubt it).

**Comment by joanyp** [comment]
I'm from Malaysia. Yea, I'm using Google DNS too to access MangaDex. The "bypass DNS protection" is turned on, so its not helping with the error. 

Oh well, at least it works with VPN, haha. Thanks for the prompt response to each messages! Really appreciate it!
